spring:
  application:
    name: Forum API
  #spring boot admin
  boot:
    admin:
      client:
        url: http://localhost:8081

  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/forumAPI
    username: postgres
    password: password

  #JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true #corrige bug do hibernate dessa versão

#JWT
forum:
  jwt:
    secret: forumAPI
    expiration: 8640000

  # actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    description: '@project.description@'